AllCops:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'config/puma.rb'
    - 'db/schema.rb'
    - 'Guardfile'
  TargetRubyVersion: 2.7.1
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/MethodLength: 
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false